In [2]:
from numpy import random

i = random.randint(10)       #int number

print(i)

7


In [4]:
from numpy import random

i = random.rand()             #float number

print(i)

0.6753828458980887


In [6]:
from numpy import random

i = random.rand(11)

print(i)

[0.97697052 0.3135671  0.51040949 0.21884319 0.01659852 0.81508453
 0.2922894  0.73642045 0.8919258  0.09411538 0.41395546]


In [8]:
from numpy import random

i = random.randint(100, size=(10))                     #generate 10 random int from 0 to 100     

print(i)

[40  5 81 71 20 88  2 89 76 10]


In [10]:
from numpy import random

i = random.randint(100, size=(3, 5))             #generate 2-D array with 3 rows

print(i)

[[10 20 84 36 42]
 [40 45 99 20 74]
 [27 50 43 29 47]]


In [12]:
from numpy import random

i = random.randint(100, size=(5, 5))           #generate 2-D array with 3 rows

print(i)

[[81 94 61 43 92]
 [ 0  7 46 93 61]
 [ 3 85 12 79 73]
 [19 37 67 97 95]
 [78 38 77 49 10]]


In [13]:
from numpy import random

i = random.randint(100, size=(3, 5, 2))

print(i)

[[[65 89]
  [48 49]
  [73 44]
  [32 20]
  [13  7]]

 [[98 75]
  [87 84]
  [28 32]
  [91 90]
  [ 8 13]]

 [[93 21]
  [22 78]
  [49 48]
  [32 99]
  [ 3  6]]]


In [14]:
from numpy import random

i = random.rand(3, 5)

print(i)

[[0.50443922 0.75009958 0.62660138 0.93851183 0.12536086]
 [0.04176804 0.69685451 0.80225597 0.89721535 0.26320252]
 [0.04646703 0.1623153  0.47392421 0.27879036 0.20573301]]
